version: "3.8"
services:
  redis:
     image: redis:5.0.12
     container_name: redis    
     command: redis-server --requirepass password
     ports:
       - 6378:6379 

  mongodb:
      image: mongo:latest   
      container_name: mongo
      restart: unless-stopped
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password     
      expose:
        - 27017    
      ports:
        - 27017:27017      
      volumes:
        - type: volume
          source: mongo_data 
          target: /data/db 
    
  service_demo_1:
    container_name: service-demo-1
    build:
      context: .
      dockerfile: Dockerfile.service-demo-1 
    image: service-demo-1
    ports:
      - "4000:4000"

  service_demo_2:
    container_name: service-demo-2
    build:
      context: .
      dockerfile: Dockerfile.service-demo-2 
    image: service-demo-2
    ports:
      - "4500:4500"

  service_demo_3:
    container_name: service-demo-3
    build:
      context: .
      dockerfile: Dockerfile.service-demo-3 
    image: service-demo-3
    ports:
      - "5500:5500"


volumes:
  mongo_data:       